# docker-compose.yml
services:
  nginx:
    image: nginx:alpine
    ports:
          - "8000:80"   # HTTP
          - "443:443"   # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api
      - prometheus 
      - grafana 
  api:
    build:
      context: .
      dockerfile: ./serve/Dockerfile.prod
    expose:
      - "8000"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus
    expose:  # Only accessible from nginx
      - "9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:8000/prometheus/'
      - '--web.route-prefix=/'

  grafana:
    image: grafana/grafana
    expose:  # Only accessible from nginx
      - "3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true