# nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    upstream api {
        server api:8000;
    }

    server {
        listen 80;

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

        location /v1/predict {
            limit_req zone=api_limit burst=20;
            proxy_pass http://api;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://api/health;
        }
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/;
        }
    }
}
