events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    upstream api_service {
        server api:8000;
    }

    server {
        listen 80;

        # API Prediction
        location /predict {
            limit_req zone=api_limit burst=20;
            proxy_pass http://api_service/predict;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health Check
        location /health {
            proxy_pass http://api_service/health;
        }

        # Grafana
        location /grafana/ {
            proxy_set_header Host $host;
            proxy_pass http://grafana:3000; 
            # Note: No trailing slash on proxy_pass when using subpaths 
            # and GF_SERVER_SERVE_FROM_SUB_PATH=true
        }

        # Prometheus
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
        }

        # Tell nginx where is the metrics
        location /metrics {
            proxy_pass http://api_service/metrics;
            proxy_set_header Host $host;
        }
    }
}