apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # CHANGE THIS: Use the service name and the internal port
    url: http://prometheus:9090
    isDefault: true
    editable: false